# periodically send power readings and application hints to the controller
controller_endpoint = "ms0833.utah.cloudlab.us"
# power cap in watts enforced when agent is first launched, any increase must be approved by controller
default_powercap = 15
# whether current node is primary or replica
is_primary = false
