# total power budget of the cluster in watts (all agents, excluding controller)
total_power_budget = 100
# total number of agents, will wait for all agents to start and contact controller before calculating power caps
total_agent_count = 2
# power priority, primary vs replica
power_priority = "primary_replica"

# hardcoded constants, may support others in future:

# algorithm to use to enforce power cap on the agent, wattson's job is only to monitor and calculate power caps
algorithm = "RAPL"
# power mode, conservative ensures that the power usage doesn't exceed the total budget at any point
# (note that we currently don't support node failures and leader elections)
power_mode = "conservative"
